---
- name: Remove ubuntu-desktop
  apt:
    name: ubuntu-desktop
    state: absent
    purge: true
- name: Remove gnome-desktop
  apt:
    name: gnome-desktop3-data
    state: absent
    purge: true
- name: Remove gnome shell
  apt:
    name: gnome shell
    state: absent
    purge: true
- name: Remove display manager
  apt:
    name: gdm3
    state: absent
    purge: true
    autoremove: true
    autoclean: true
- name: Set default target
  command: systemctl set-default multi-user.target
- name: Reboot
  reboot:
